name: rpg_management
description: Um sistema para gerenciar personagens e itens mágicos de RPG.
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
dependencies:
  ansi_styles: ^0.3.2+1
